### ISSUE TITLE
resource references

### ISSUE THREAD

**Issue by ShrikanthSingh** [susantabiswas/Word-Prediction-Ngram#3]
Hey Susanta,
Do you have any theory references for the implementation, as I am not able to understand the notations used and also the purpose of some functions for eg: findBestFitIntercept, findBestFitSlope.
Thank you

**Comment by susantabiswas** [comment]
Hi Shrikanth, It's been a long time since I have worked on this, so don't remember much about all the resources and papers followed. I do remember using this deck from Dan Jurafsky,  this deck should have most of the conventions and notations: 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjU1pjQ5pHvAhVPzjgGHYjjCKgQFjAAegQIAxAD&url=https%3A%2F%2Fweb.stanford.edu%2F~jurafsky%2Fslp3%2Fslides%2FLM_4.pdf&usg=AOvVaw2DTqkt3hDfMhfBcFMKNBNb

**Comment by ShrikanthSingh** [comment]
> Hey Susanta,
> Do you have any theory references for the implementation, as I am not able to understand the notations used and also the purpose of some functions for eg: findBestFitIntercept, findBestFitSlope.
> Thank you

Just in case someone needs a step by step explanation refer to:
[http://www.deepsky.com/~merovech/voynich/voynich_manchu_reference_materials/PDFs/jurafsky_martin.pdf](url)
